### ISSUE TITLE
CSV import assigns arbitrary time import date 

### ISSUE THREAD

**Issue by stalsma** [assetgrid/assetgridapp#52]
I was playing around with a docker instance, and created an import, pulling in account data from several sources.

Each transaction is assigned a time (either 10PM or 11PM) despite no time being present in the CSV file.  And in the span of a single import, I received both times on the imported transactions.
![Screenshot 2022-10-19 104908](https://user-images.githubusercontent.com/5501817/196643439-48d1ae53-e73c-407a-ba05-81c55c469e52.png)

**Comment by alex6480** [comment]
Thanks for the report. Which database are you using?

**Comment by alex6480** [comment]
The issue is fixed in Assetgrid v0.2.1

**Comment by stalsma** [comment]
Hmmm--I pulled 'latest' from docker.  Is that an older version?
![image](https://user-images.githubusercontent.com/5501817/196735656-ce563763-00c8-46b8-9238-aa3f679885e6.png)

**Comment by alex6480** [comment]
The latest version says "Assetgrid v0.2.1" in the sidebar. Pulling assetgrid:latest should be fine. I pushed the release around 2 hours ago.

Unfortunately you will need to reimport your transactions to fix the issue. Newly create transactions should work.
If the issue persists, let me know.

**Comment by stalsma** [comment]
Hmmm.  Somethings not updating on the docker side.  I deleted my instance (keeping the data folder), and created a new container:

```
docker run -d --name=assetgrid \
-p 5160:8080 \
-v /volume1/docker/assetgrid:/usr/share/assetgrid/assetgrid_data \
--restart always \
assetgrid/assetgrid
```

I still see the import time as 11PM (assuming this has to do w/time zone?) and no version in the sidebar.

![image](https://user-images.githubusercontent.com/5501817/196894394-8ced7944-6c75-4976-9848-d61a6fb448ea.png)

**Comment by alex6480** [comment]
Did you run the following?

    docker --pull assetgrid/assetgrid

Docker caches images, so unless you explicitly pull them it will reuse the old version.

**Comment by stalsma** [comment]
I deleted the old container and image.  Maybe something on Docker side?

Task: Install AssetGrid
Start time: Thu, 20 Oct 2022 11:38:56 GMT
Stop time: Thu, 20 Oct 2022 11:39:14 GMT
Current status: 0 (Normal)
Standard output/error:
latest: Pulling from assetgrid/assetgrid
bd159e379b3b: Already exists
e55a07b7e890: Already exists
a16a4246d064: Already exists
d3f506b68202: Already exists
448cf92f0417: Already exists
65d2167920a3: Pulling fs layer
c86451e08c7b: Pulling fs layer
4f4fb700ef54: Pulling fs layer
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
c86451e08c7b: Verifying Checksum
c86451e08c7b: Download complete
65d2167920a3: Download complete
65d2167920a3: Pull complete
c86451e08c7b: Pull complete
4f4fb700ef54: Pull complete
Digest:
sha256:a01f7c6224dc5af0fe944c302523b4aa4194d4347da272372f1eeca07299218b
*Status: Downloaded newer image for assetgrid/assetgrid:latest*
b91071d45055cff7f26fe7d460d432b9a3a02ce90aaa3d3bb9281f4dd6ea7e63

**Comment by alex6480** [comment]
It is not the latest version.
You can see the digest of the latest version on docker hub
![billede](https://user-images.githubusercontent.com/8026279/196920444-33dbbc33-29ef-436e-b9f1-b7146a5e161c.png)

Once updated it will look like this:
![billede](https://user-images.githubusercontent.com/8026279/196920635-a06a16b3-17a3-46e3-b069-1f962130c340.png)
